### ISSUE TITLE
FR change controls

### ISSUE THREAD

**Issue by CrimsonFork** [HassanHeydariNasab/trans#2]
I'd like the robot to follow my finger instead of having buttons to change the dirrection.

**Comment by HassanHeydariNasab** [comment]
It seems hard to implement. Did you think about rotating?

**Comment by braniii** [comment]
I think it's quite easy to implement? At least I managed with a few lines, that it follows my cursor if I'm pressing any specified key. Can you tell me, how the touch event works?
If I have time those days, I'll configure Godot to try it on my mobile. If it works, I'll make a pull request.

**Comment by braniii** [comment]
I think it's quite easy to implement, isn't it? At least I managed with a few lines, that it follows my cursor if I'm pressing any specified key. Can you tell me, how the touch event works?
If I have time those days, I'll configure Godot to try it on my mobile. If it works, I'll make a pull request.

**Comment by CrimsonFork** [comment]
Maybe make a GUI circle for controlling the dirrection and put it on the bottom so you don't cover 1/3 of your screen every once you want to go upwards? Should be basically the same when talking about the coding.

**Comment by braniii** [comment]
#6 I'm sorry for the delay, but I was busy. I wasn't able to try it on a touch device, but I hope it works there, too. I would also suggest to implement the boost via double click, to make the control even more handy.

**Comment by CrimsonFork** [comment]
I'm not sure about that, I think that it's best to put the boost button somewhere on the lower half of the screen and take it ad the middle to change your dirrection by tapping or holding anywhere outside.

On October 16, 2017 7:11:57 PM GMT+02:00, braniii <notifications@github.com> wrote:
>#6 I'm sorry for the delay, but I was busy. I wasn't able to try it on
>a touch device, but I hope it works there, too. I would also suggest to
>implement the boost via double click, to make the control even more
>handy.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/HassanHeydariNasab/trans/issues/2#issuecomment-336956208

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by HassanHeydariNasab** [comment]
I just implemented "double click/tap for boost"
https://github.com/HassanHeydariNasab/trans/commit/acf6b8f578c4f36e7c5408a0d376650b14cce062

**Comment by CrimsonFork** [comment]
Cool.

On December 24, 2017 9:13:14 AM GMT+01:00, Hasan Hejdari Nasab <notifications@github.com> wrote:
>I just implemented "double click/tap for boost"
>https://github.com/HassanHeydariNasab/trans/commit/acf6b8f578c4f36e7c5408a0d376650b14cce062
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/HassanHeydariNasab/trans/issues/2#issuecomment-353771541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
