### ISSUE TITLE
Health bar not changing

### ISSUE THREAD

**Issue by CrimsonFork** [HassanHeydariNasab/trans#3]
The boss' health bar doesn't change when it gets damage.

**Comment by HassanHeydariNasab** [comment]
Are you sure?
How many bombs did you test? (it should killed by 12 bombs)

**Comment by CrimsonFork** [comment]
I was sure untill I recorded it. Only then I noticed that it gets smaller and smaller. This difference is to small to notice during gameplay.

It'd be way easier if it was something more progress bar like, just as the player's ressources.
