### ISSUE TITLE
FR change the Boss' behavior

### ISSUE THREAD

**Issue by CrimsonFork** [HassanHeydariNasab/trans#5]
It's physically impossible to beat the boss without the powerupps collected before because it's faster than you and perfectly homing in.

I generally don't like being forced to collect something in a game. I prefer much more having some benefits from collecting the stuff but being able to handle anything with your skill anyway.

That's why I suggest turning down the homing to ~50% and make the boss a little faster so it misses you if you make sudden changes of the dirrection.

Also I suggest making time to energy, it just makes more sense (to me) that you die when you have no energy left.

**Comment by HassanHeydariNasab** [comment]
Next Bosses will be in a maze!
