### ISSUE TITLE
Blank Maze?

### ISSUE THREAD

**Issue by valerio-bozzolan** [HassanHeydariNasab/trans#7]
First of all, thanks for your work. I'm really appreciating it from F-Droid :)

Is it normal that in `2.1.0.alpha1` the Maze is actually blank with no time and nothing to pick? :)

![Maze](https://user-images.githubusercontent.com/6052909/31845314-ce5ed748-b5ff-11e7-9682-a85b1f9bf4e9.png)

**Comment by HassanHeydariNasab** [comment]
Yes, it's normal. it's a placeholder and nothing more! alpha is alpha!

**Comment by valerio-bozzolan** [comment]
OK thanks :)
